### ISSUE TITLE
Use the actual file name in "Content-Disposition" header

### ISSUE THREAD

**Issue by StrawBerryAtWork** [RedFroggy/spring-cucumber-rest-api#69]
Hello,

I have noticed that the upload of a file rule is not setting the file name in "Content-Disposition" header and using the part name.

It should set the actual file name uploaded.

This means we will be able to test the file name in the endpoint.

For example, I want to test extension of csv files.

François
Sis ID

**Comment by StrawBerryAtWork** [comment]
I have made some modification, if you want to review it, please tell me how to create a pull request.

**Comment by michaeldesigaud** [comment]
@StrawBerryAtWork To make a PR, you need to:
- Fork this project
- Create a new branch from your fork and push your code
- Open a PR in github from your fork branch to this repo (master branch)
More info here: https://www.dataschool.io/how-to-contribute-on-github/

Thanks again for this !
